---
language: python
services: docker

env:
  global:
    - ROLE_NAME: pms

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: jcalavia-org:UaZ60aCeDgo6ISl60fd5vgXf
